### ISSUE TITLE
No existe el paquete gitbook-start-heroku-ull-es-aitor-joshua-samuel

### ISSUE THREAD

**Issue by DanielRamosAcosta** [ULL-ESIT-SYTW-1617/autenticacion-oauth-con-passport-aitor-joshua-samuel#2]
# tl;dr
Cuando se despliega con heroku, la tarea que se crea requiere el paquete `gitbook-start-heroku-ull-es-aitor-joshua-samuel`, pero este paquete no está instalado y no existe en npmjs.

```
node -v; npm -v
v7.1.0
3.10.9
```

# Pasos
1. `npm i -g gitbook-start-iaas-aitor-joshua-samuel`
2. `gitbook-start -n correccionSamuel`
3. `cd correccionSamuel`
4. `git init; git add .; git commit -m "Primer commit"`
5. `nano userData.json`
   ```
   {
       "org": "ULL-ESIT-GRADOII-DSI",
       "token": "............................."
   }
   ```
6. `gitbook-start -d heroku`
7. `cat gulpfile.js`

   Salida:

   ```JavaScript
   //Dependencias
   var gulp = require('gulp');
   var ghPages = require('gulp-gh-pages');
   var exec = require('child_process').exec;
   var shell = require('gulp-shell');

   gulp.task('deploy', function() {
     return gulp.src(['_book/*/*/*','_book/*/*','_book/*'])
       .pipe(ghPages());
   });

   gulp.task('deploy-github', shell.task([
     'git add .',
     'git commit -m "modificando"',
     'git push origin master'
   ]));
   var heroku = require('gitbook-start-heroku-ull-es-aitor-joshua-samuel');
   gulp.task('deploy-heroku',function() {
       heroku.deploy();
   });
   ```
8. `gulp deploy-heroku`

   Salida:

   ```
   module.js:474
       throw err;
       ^

   Error: Cannot find module 'gitbook-start-heroku-ull-es-aitor-joshua-samuel'
       at Function.Module._resolveFilename (module.js:472:15)
       at Function.Module._load (module.js:420:25)
       at Module.require (module.js:500:17)
       at require (internal/module.js:20:19)
       at Object.<anonymous> (/home/daniel/Documentos/Repos/Ajenos/correccionSamuel/gulpfile.js:17:14)
       at Module._compile (module.js:573:32)
       at Object.Module._extensions..js (module.js:582:10)
       at Module.load (module.js:490:32)
       at tryModuleLoad (module.js:449:12)
       at Function.Module._load (module.js:441:3)

   ```
9. `npm i -D gitbook-start-heroku-ull-es-aitor-joshua-samuel`

   Salida:

   ```
   npm ERR! Linux 4.8.0-27-generic
   npm ERR! argv "/home/daniel/.config/fnm/bin/node" "/home/daniel/.config/fnm/bin/npm" "i" "gitbook-start-heroku-ull-es-aitor-joshua-samuel"
   npm ERR! node v7.1.0
   npm ERR! npm  v3.10.9
   npm ERR! code E404

   npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/gitbook-start-heroku-ull-es-aitor-joshua-samuel
   npm ERR! 404 
   npm ERR! 404  'gitbook-start-heroku-ull-es-aitor-joshua-samuel' is not in the npm registry.
   npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
   npm ERR! 404 
   npm ERR! 404 Note that you can also install from a
   npm ERR! 404 tarball, folder, http url, or git url.

   npm ERR! Please include the following file with any support request:
   npm ERR!     /home/daniel/Documentos/Repos/Ajenos/correccionSamuel/npm-debug.log

   ```

Y efectivamente el plugin [`gitbook-start-heroku-ull-es-aitor-joshua-samuel`](https://www.npmjs.com/package/gitbook-start-heroku-ull-es-aitor-joshua-samuel) no existe.

**Comment by Losnen** [comment]
Perdón, ya está solucionado, vuelve a instalar gitbook-start de nuevo, cualquier otro problema me avisas.

**Comment by DanielRamosAcosta** [comment]
De nada! Vale, entonces ahora hago lo siguiente, a partir del paso 5 de antes:

6. `npm install --save gitbook-start-heroku-aitor-joshua-samuel`
7. `gitbook-start -d heroku -p github`

   Salida:
   ```
   [master 29e155e] Modificando
    7 files changed, 252 insertions(+), 52 deletions(-)
    create mode 100644 node_modules/gitbook-start-heroku-aitor-joshua-samuel/.npmignore
    create mode 100644 node_modules/gitbook-start-heroku-aitor-joshua-samuel/README.md
    create mode 100644 node_modules/gitbook-start-heroku-aitor-joshua-samuel/index.js
    create mode 100644 node_modules/gitbook-start-heroku-aitor-joshua-samuel/package.json
    create mode 100644 node_modules/gitbook-start-heroku-aitor-joshua-samuel/template/Procfile
    create mode 100644 node_modules/gitbook-start-heroku-aitor-joshua-samuel/template/index.js
    rewrite package.json (99%)

   fatal: 'heroku' does not appear to be a git repository
   fatal: Could not read from remote repository.

   Please make sure you have the correct access rights
   and the repository exists.

    ▸    Error: No app specified
    ▸    Usage: heroku open [PATH] --app APP
    ▸    We don't know which app to run this on.
    ▸    Run this command from inside an app folder or specify which app to use with --app APP
    ▸    
    ▸    https://devcenter.heroku.com/articles/using-the-cli#app-commands

    !    `ps:scale=1` is not a heroku command.
    !    Perhaps you meant `ps:scale`.
    !    See `heroku help` for a list of available commands.
   ```

Miren a ver y me avisan plis.

**Comment by DanielRamosAcosta** [comment]
Uf espera creo que tenía otro paquete instalado, un segundo.

**Comment by Losnen** [comment]
La versión que debería tener es la 1.1.1

**Comment by DanielRamosAcosta** [comment]
Vale vale, tenía instalado el que era, me da el mismo fallo. Del paquete principal tengo la `2.1.3`, y del `gitbook-start-heroku-aitor-joshua-samuel` la 0.0.1. Instalo entonces la 1.1.1 del paquete principal?

**Comment by Losnen** [comment]
Del paquete principal la ``` 3.3.1 ```
Del plugin heroku la ``` 1.1.1 ```

**Comment by DanielRamosAcosta** [comment]
Pero la versión del paquete principal que me estás diciendo no existe, de hecho se supone que `npm` instala la última disponible. Del [`gitbook-start-iaas-aitor-joshua-samuel`](https://www.npmjs.com/package/gitbook-start-iaas-aitor-joshua-samuel) (principal) la última publicada es la `2.1.3`. Estoy instalando el que no es?

**Comment by Losnen** [comment]
El paquete que tienes que instalar ```[gitbook-start-aitor-joshua-samuel](https://www.npmjs.com/package/gitbook-start-aitor-joshua-samuel)```

**Comment by DanielRamosAcosta** [comment]
Oook, voy a intentarlo con ese ahora

**Comment by DanielRamosAcosta** [comment]
Vaaale había instalado esa versión porque era el enlace que estaba en el aula. Bueno, ahora con la versión `3.3.1` del principal y la `1.1.1` del plugin pasa esto:

```
$ gitbook-start -d heroku -p github
? Introduce tu token de Heroku:  37e279f0-2068-40ba-a848-60e99e55e0df
? Introduzca el nombre de su app en Heroku:  correcSamuel
Ficheros de Heroku desplegados
Aplicación creada: correcSamuel
(node:3735) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Expected response to be successful, got 422
(node:3735) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Losnen** [comment]
Creo que es porque la aplicación ya está creada, porque no implementamos los errores, no sabiamos como, prueba con otro nombre y deberia funcionar

**Comment by DanielRamosAcosta** [comment]
No pero es que antes no la llegó a crear, y por si acaso esta vez le puse el nombre `correcSamuel` en vez de `correccionSamuel`. Si tal prueba hacer un `.catch` en la promesa del [`h.post`](https://github.com/ULL-ESIT-SYTW-1617/gitbook-start-heroku-aitor-joshua-samuel/blob/master/index.js#L51) e imprimir el `token` y el `name` a ver que pasa.

**Comment by Losnen** [comment]
A mi me las está creando sin problema alguno, que raro

**Comment by Losnen** [comment]
Ademas acabo de comprobar el token y el name se los pasa correctamente

**Comment by DanielRamosAcosta** [comment]
Vale un momento, corrigiendo la de Eric creo que es porque el nombre de la App tiene mayúsculas, cuando termine con él vuelvo.

**Comment by DanielRamosAcosta** [comment]
Vale ahora funciona un poco mejor. Ya salta de donde estábamos antes, y crea la aplicación. Añade la tarea al gulpfile (lo que está duplicada, así que eliminé una). Hice un `gulp deploy-heroku` y no dió ningun error.

El problema es que en la [aplicación](https://correccionsamu.herokuapp.com/) no sale nada, y `heroku logs` tampoco dice mucho:
```
2016-11-23T20:31:58.839054+00:00 heroku[slug-compiler]: Slug compilation started
2016-11-23T20:31:58.839058+00:00 heroku[slug-compiler]: Slug compilation finished
2016-11-23T20:32:00.867381+00:00 heroku[web.1]: Starting process with command `node server.js`
2016-11-23T20:32:03.353979+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2016-11-23T20:32:03.353990+00:00 app[web.1]: designed for a production environment, as it will leak
2016-11-23T20:32:03.353991+00:00 app[web.1]: memory, and will not scale past a single process.
2016-11-23T20:32:03.357520+00:00 app[web.1]: App running on localhost:3000
2016-11-23T20:33:00.984505+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2016-11-23T20:33:00.984606+00:00 heroku[web.1]: Stopping process with SIGKILL
2016-11-23T20:33:01.075895+00:00 heroku[web.1]: Process exited with status 137
2016-11-23T20:33:01.094117+00:00 heroku[web.1]: State changed from starting to crashed
2016-11-23T20:33:01.095428+00:00 heroku[web.1]: State changed from crashed to starting
2016-11-23T20:33:02.718728+00:00 heroku[web.1]: Starting process with command `node server.js`
2016-11-23T20:33:04.640275+00:00 app[web.1]: Warning: connect.session() MemoryStore is not
2016-11-23T20:33:04.640307+00:00 app[web.1]: designed for a production environment, as it will leak
2016-11-23T20:33:04.640308+00:00 app[web.1]: memory, and will not scale past a single process.
2016-11-23T20:33:04.645855+00:00 app[web.1]: App running on localhost:3000
```

**Comment by Losnen** [comment]
Estoy echando un ojo a ver `por que puede ser.

**Comment by Losnen** [comment]
Parece ser que es un problema de heroku con express-sessions segun stackoverflow, porque en local me funciona bien

**Comment by DanielRamosAcosta** [comment]
Es por el warning de `Warning: connect.session() MemoryStore`?

**Comment by Losnen** [comment]
Entiendo que es eso, porque funciona perfectamente ejecutando ```heroku local``` funciona bien, el warning ese es de (````express-sessions````)[https://www.npmjs.com/package/express-session] Pero no encuentro ninguna solución al respecto por el momento

**Comment by DanielRamosAcosta** [comment]
Bueno, cierro este issue ya que al final el paquete sí se encuentra, y abro el #3. Ya mañana lo miramos en clase o algo.
